name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}

    - name: Get dependencies
      run: |
        go get -v -t github.com/${{ github.repository }}/...

    - name: Build
      run: go build -v github.com/${{ github.repository }}/...

    - name: Test
      run: go test -v github.com/${{ github.repository }}/...
